export const UPLOAD_CANDIDATES = 'UPLOAD_CANDIDATES';

export const SET_UPLOADED_CANDIDATES = 'SET_UPLOADED_CANDIDATES';

export const GET_CANDIDATES = 'GET_CANDIDATES';

export const SET_CANDIDATES = 'SET_CANDIDATES';

export const SET_ERRORS = 'SET_ERRORS';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const SET_SELECTED_CANDIDATE = 'SET_SELECTED_CANDIDATE';

export const FETCH_CANDIDATE = 'FETCH_CANDIDATE';

export const GET_CANDIDATE_PROGRAMS = 'GET_CANDIDATE_PROGRAMS';

export const SET_CANDIDATE_PROGRAMS = 'SET_CANDIDATE_PROGRAMS';
