image: maven:3.6.3-jdk-11
stages:
  - clean
  - checkstyle
  - test
  - code_coverage
  - build

clean:
  stage: clean
  script:
    - mvn clean
  only:
    - merge_requests

checkstyle:
  stage: checkstyle
  script:
    - mvn checkstyle:check
  only:
    - merge_requests
  dependencies:
    - clean

test:
  stage: test
  script:
    - mvn test jacoco:report
  artifacts:
    paths:
      - target/surefire-reports/TEST*.xml
      - target/site/jacoco
    reports:
      junit:
        - target/surefire-reports/TEST*.xml
  only:
    - merge_requests

code_coverage:
  stage: code_coverage
  image: haynes/jacoco2cobertura:1.0.4
  script:
    - 'python /opt/cover2cover.py target/site/jacoco/jacoco.xml src/main/java > target/site/cobertura.xml'
    - 'python /opt/source2filename.py target/site/cobertura.xml'
  needs: ["test"]
  only:
    - merge_requests
  dependencies:
    - test
  artifacts:
    reports:
      cobertura: target/site/cobertura.xml

build:
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - target/resoft-0.0.1-SNAPSHOT.jar
  only:
    - develop
