export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const SET_ERRORS = 'SET_ERRORS';

export const SET_UPLOADED_ACTIVITIES_EVALUATIONS =
  'SET_UPLOADED_ACTIVITIES_EVALUATIONS';

export const UPLOAD_ACTIVITIES_EVALUATIONS = 'UPLOAD_ACTIVITIES_EVALUATIONS';

export const GET_EVALUATIONS_RESULT = 'GET_EVALUATIONS_RESULT';

export const SET_EVALUATIONS_RESULT = 'SET_EVALUATIONS_RESULT';
