export const UPLOAD_ACTIVITIES = 'UPLOAD_ACTIVITIES';

export const SET_UPLOADED_ACTIVITIES = 'SET_UPLOADED_ACTIVITIES';

export const SET_ERRORS = 'SET_ERRORS';

export const GET_ACTIVITIES = 'GET_ACTIVITIES';

export const SET_ACTIVITIES = 'SET_ACTIVITIES';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
