export const FETCH_PROGRAMS = 'FETCH_PROGRAMS';

export const SET_PROGRAMS = 'SET_PROGRAMS';

export const CLEAR_PROGRAMS = 'CLEAR_PROGRAMS';

export const IMPORT_PROGRAMS = 'IMPORT_PROGRAMS';

export const SET_IMPORT_PROGRAMS = 'SET_IMPORT_PROGRAMS';

export const SET_ERRORS = 'SET_ERRORS';

export const GET_PROGRAM = 'GET_PROGRAM';

export const SET_PROGRAM = 'SET_PROGRAM';

export const CLEAR_PROGRAM = 'CLEAR_PROGRAM';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const UPDATE_PROGRAM = 'UPDATE_PROGRAM';

export const SET_PROGRAM_TO_EDIT = 'SET_PROGRAM_TO_EDIT';
