export const IMPORT_STAGES = 'IMPORT_STAGES';

export const IMPORT_STAGES_SUCCESS = 'IMPORT_STAGES_SUCCESS';

export const SET_STAGES_ERROR = 'SET_STAGES_ERROR';

export const SET_SELECTED_PROGRAM_STAGES = 'SET_SELECTED_PROGRAM_STAGES';

export const FETCH_PROGRAM_STAGES = 'FETCH_PROGRAM_STAGES';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const UPDATE_PROGRAM_STATES = 'UPDATE_PROGRAM_STATES';

export const UPDATE_STAGE = 'UPDATE_STAGE';
